name: Publish Python Wheel

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Publish Python Wheel 📦 to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Set VERSION
        run: |
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Fetch Python Wheel
        uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{ github.ref_name }}
          fileName: rootcanal-${{ env.VERSION }}-py3-none-any.whl
          out-file-path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
